version: '3.9'
services:
  laravel.test:
    build:
      context: ./
      dockerfile: Dockerfile
    image: composer-mysql
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - '.:/var/www/html'
    working_dir: '/var/www/html'
    networks:
      - sail
    # Always start with a freshly migrated database
    entrypoint: 'bash -c "composer install && php artisan migrate:fresh && php artisan serve --host=0.0.0.0 --port=80"'
    depends_on:
      - node
      - mysql
    healthcheck:
      test: 'curl localhost:80'

  node:
    image: 'node:15.12.0-buster'
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - ./rest-api-server:/home/node/app
    networks:
      - sail
    ports:
      - '${REST_API_SERVER_PORT:-8081}:8081'
    command: 'node .'
    healthcheck:
      test: 'curl localhost:8081'

  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'sailmysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

networks:
  sail:
    driver: bridge

volumes:
  sailmysql:
    driver: local